name: Deploy Azure Function

on:
  push:
    branches:
      - Production

jobs:
  build-and-deploy-function:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout código
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: 📦 Instalar dependências da Function
        shell: bash
        run: |
          cd functions
          npm install

      - name: 🔐 Login na Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 🚀 Deploy para Azure Function
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNC_NAME }}
          package: ./functions